server:
  port: 8100

spring:
  application:
    name: kiba-jpa-demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/kiba_demo_db
    username: postgres
    password: password
    initialization-mode: always
    platform: postgres
